# Changes here will be overwritten by Copier
_commit: v0.2.0
_src_path: gh:alan-turing-institute/python-project-template
coc: our_coc
email: edable-heath@turing.ac.uk
full_name: Edmund Dable-Heath
license: MIT
min_python_version: '3.10'
org: alan-turing-institute
project_name: ARC-phash
project_short_description: An investigatory repo exploring the relationship between
    perceptual hashing and in-painting
python_name: arc_phash
typing: loose
url: https://github.com/alan-turing-institute/ARC-phash
